#!/bin/bash

# usage
if [ $# != 3 ] ; then
  echo -e "Usage: ${0} <major|minor|update> <source_branch> <release_branch>"
  exit 1
fi

current_branch="$(pwb)"
updateType="${1}"
source_branch="${2}"
branch="${3}"

echo "INFO: Fetching..."
if ! git fetch --all --tags ; then
  echo "ERROR: Failed to fetch all tags!"
  exit 1
fi


# cleanup trap
function cleanup {
  echo "INFO: Checking out previous ${branch}..."
  git checkout "${current_branch}"
}
trap cleanup EXIT


echo
if [ "${source_branch}" == "${branch}" ] ; then
  echo "INFO: Already on branch ${source_branch}..."
else
  echo "INFO: Checking out ${source_branch}..."
  if ! git checkout "${source_branch}" ; then
    echo "ERROR: Failed to checkout branch ${source_branch}"
    exit 1
  fi

  echo "INFO: Rebasing origin/${source_branch}..."
  if ! git rebase "origin/${source_branch}" ; then
    echo "ERROR: Failed to rebase ${source_branch}!"
    exit 1
  fi
fi


echo
echo "INFO: Checking out target ${branch}..."
if ! git checkout "${branch}" ; then
  echo "WARN: Failed to checkout target branch ${branch}"
  echo -e "WARN: Do you want to create target branch ${branch} from branch ${source_branch}? [Y/n]"
  read a
  if [[ "${a}" != "" ]] && [[ "${a}" != "y" ]] ; then
    exit 0
  fi

  if ! git checkout -b "${branch}" "${source_branch}" ; then
    echo "ERROR: Failed to create new branch ${branch}"
    exit 1
  fi

  echo "INFO: Pushing new branch to origin..."
  if ! git push --set-upstream origin "${branch}" ; then
    echo "ERROR: Failed to push new branch ${branch} to origin!"
    exit 1
  fi
fi


# rebasing
echo "INFO: Rebasing origin/${branch}..."
if ! git rebase "origin/${branch}" ; then
  echo "ERROR: Failed to rebase ${branch}!"
  exit 1
fi


# merge branchs
if [ "${source_branch}" == "${branch}" ] ; then
  echo "INFO: Source and release branch are the same not merging: ${source_branch}"
else
  echo "INFO: Merging ${source_branch}..."
  if ! GIT_EDITOR=: git merge ${source_branch} ; then
    echo "ERROR: Failed to prepare repo for auto release!"
    exit 1
  fi
fi


# have user update pom.xml if necessary
echo -n "INFO: Merge complete. Please update versions in pom.xml: <enter>"
read a
if ! editor ./pom.xml ; then
  echo "ERROR: pom.xml failed"
  exit 1
fi


# commit changes
if output=$(git status --porcelain) && [ -z "$output" ]; then
  echo "INFO: No changes in pom.xml, no commit needed."
else
  git add pom.xml
  if ! git commit -m "[Project] Update pom.xml in auto release" ; then
    echo "ERROR: Failed to commit changed pom.xml"
    exit 1
  fi
fi


# push changes to origin
echo "INFO: Pushing ${branch} to origin..."
if ! git push origin ${branch} ; then
  echo "ERROR: Failed to push ${branch} to origin."
  exit 1
fi


# now perform autoRelease
echo "INFO: Starting auto release on branch ${branch}..."
if ! autoRelease "${updateType}" "${branch}" ; then
  echo "ERROR: Failed to perform auto release!"
  exit 1
fi

echo "INFO: Performed auto-release on ${branch}"
exit 0
