name: "Build pull-request to main branch"

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Build:
    name: Build Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get remove --purge man-db
          sudo apt-get update
          sudo apt-get install --yes build-essential linux-headers-$(uname -r) sudo libi2c-dev linux-modules-extra-$(uname -r)

      - name: Install JDK25
        uses: sfesenko/setup-sdkman@v1
        with:
          deps: java:25-zulu

      - name: Create and add current user to suitable groups
        run: |
          sudo addgroup spi
          sudo adduser $USER spi
          sudo adduser $USER i2c
          sudo adduser $USER dialout

      - name: Add proper udev rules and trigger udevadm
        run: |
          sudo cp udev.rules /etc/udev/rules.d/99-pi4j-io.rules
          sudo udevadm control --reload-rules && sudo udevadm trigger

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build entire Pi4J Project
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: sudo -u $USER bash -c 'source ~/.sdkman/bin/sdkman-init.sh && ./mvnw clean package'

      - name: Make staging directory
        run: mkdir staging

      - name: Upload distribution files to staging
        uses: actions/upload-artifact@v4
        with:
          name: pi4j-dist
          path: staging
